In [1]:
import numpy as np
import pandas as pd

# Importing the dataset

In [2]:
dfTrain = pd.read_csv('adult.data', skipinitialspace=True)
dfTrain.columns = ["age" , "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
dfTest = pd.read_csv('adult.test', skipinitialspace=True)
dfTest.columns = ["age" , "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
dfTest["income"] = dfTest["income"].str.replace('.', '')

<ipython-input-2-8d10fcb8645b>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  dfTest["income"] = dfTest["income"].str.replace('.', '')


In [3]:
dfTrain

age         workclass  fnlwgt   education  education-num  \
0       50  Self-emp-not-inc   83311   Bachelors             13   
1       38           Private  215646     HS-grad              9   
2       53           Private  234721        11th              7   
3       28           Private  338409   Bachelors             13   
4       37           Private  284582     Masters             14   
...    ...               ...     ...         ...            ...   
32555   27           Private  257302  Assoc-acdm             12   
32556   40           Private  154374     HS-grad              9   
32557   58           Private  151910     HS-grad              9   
32558   22           Private  201490     HS-grad              9   
32559   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0      Married-civ-spouse    Exec-managerial        Husband  White    Male   
1                Divorced  Handlers-cleaners  Not-in-family  White    Male   
2      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
3      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
4      Married-civ-spouse    Exec-managerial           Wife  White  Female   
...                   ...                ...            ...    ...     ...   
32555  Married-civ-spouse       Tech-support           Wife  White  Female   
32556  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32557             Widowed       Adm-clerical      Unmarried  White  Female   
32558       Never-married       Adm-clerical      Own-child  White    Male   
32559  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              13  United-States  <=50K  
1                 0             0              40  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40           Cuba  <=50K  
4                 0             0              40  United-States  <=50K  
...             ...           ...             ...            ...    ...  
32555             0             0              38  United-States  <=50K  
32556             0             0              40  United-States   >50K  
32557             0             0              40  United-States  <=50K  
32558             0             0              20  United-States  <=50K  
32559         15024             0              40  United-States   >50K  

[32560 rows x 15 columns]

In [8]:
dfTest

age     workclass  fnlwgt     education  educationNum  \
0       38       Private   89814       HS-grad             9   
1       28     Local-gov  336951    Assoc-acdm            12   
2       44       Private  160323  Some-college            10   
3       18             ?  103497  Some-college            10   
4       34       Private  198693          10th             6   
...    ...           ...     ...           ...           ...   
16275   39       Private  215419     Bachelors            13   
16276   64             ?  321403       HS-grad             9   
16277   38       Private  374983     Bachelors            13   
16278   44       Private   83891     Bachelors            13   
16279   35  Self-emp-inc  182148     Bachelors            13   

            maritalStatus         occupation    relationship  \
0      Married-civ-spouse    Farming-fishing         Husband   
1      Married-civ-spouse    Protective-serv         Husband   
2      Married-civ-spouse  Machine-op-inspct         Husband   
3           Never-married                  ?       Own-child   
4           Never-married      Other-service   Not-in-family   
...                   ...                ...             ...   
16275            Divorced     Prof-specialty   Not-in-family   
16276             Widowed                  ?  Other-relative   
16277  Married-civ-spouse     Prof-specialty         Husband   
16278            Divorced       Adm-clerical       Own-child   
16279  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex  capitalGain  capitalLoss  hoursPerWeek  \
0                   White    Male            0            0            50   
1                   White    Male            0            0            40   
2                   Black    Male         7688            0            40   
3                   White  Female            0            0            30   
4                   White    Male            0            0            30   
...                   ...     ...          ...          ...           ...   
16275               White  Female            0            0            36   
16276               Black    Male            0            0            40   
16277               White    Male            0            0            50   
16278  Asian-Pac-Islander    Male         5455            0            40   
16279               White    Male            0            0            60   

       nativeCountry income  
0      United-States  <=50K  
1      United-States   >50K  
2      United-States   >50K  
3      United-States  <=50K  
4      United-States  <=50K  
...              ...    ...  
16275  United-States  <=50K  
16276  United-States  <=50K  
16277  United-States  <=50K  
16278  United-States  <=50K  
16279  United-States   >50K  

[16280 rows x 15 columns]

In [4]:
print('train length = ', len(dfTrain))
print('test length = ', len(dfTest))

train length =  32560
test length =  16280


# Remove records with unknown values

In [3]:
dfTrain = dfTrain[(dfTrain.values != '?').all(axis=1)]
dfTest = dfTest[(dfTest.values != '?').all(axis=1)]

In [6]:
print('train length = ', len(dfTrain))
print('test length = ', len(dfTest))

train length =  30161
test length =  15059


# Encoding categorical data

In [4]:
def oneHotBind(original_dataframe, feature_to_encode):
    dummies = pd.get_dummies(original_dataframe[feature_to_encode])
    res = pd.concat([original_dataframe, dummies], axis=1)
    res = res.drop(feature_to_encode, axis=1)
    return (res)

In [5]:
dfTrain = oneHotBind(dfTrain, ["workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country"])
dfTest = oneHotBind(dfTest, ["workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country"])

In [6]:
dfTrain.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   50   83311             13             0             0              13   
1   38  215646              9             0             0              40   
2   53  234721              7             0             0              40   
3   28  338409             13             0             0              40   
4   37  284582             14             0             0              40   

  income  workclass_Federal-gov  workclass_Local-gov  workclass_Private  ...  \
0  <=50K                      0                    0                  0  ...   
1  <=50K                      0                    0                  1  ...   
2  <=50K                      0                    0                  1  ...   
3  <=50K                      0                    0                  1  ...   
4  <=50K                      0                    0                  1  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                        0                           0   
1                        0                           0   
2                        0                           0   
3                        0                           0   
4                        0                           0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                        0                     0                      0   
1                        0                     0                      0   
2                        0                     0                      0   
3                        0                     0                      0   
4                        0                     0                      0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                        0                               0   
1                        0                               0   
2                        0                               0   
3                        0                               0   
4                        0                               0   

   native-country_United-States  native-country_Vietnam  \
0                             1                       0   
1                             1                       0   
2                             1                       0   
3                             0                       0   
4                             1                       0   

   native-country_Yugoslavia  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  

[5 rows x 105 columns]

# Transform numerical attribute

In [7]:
def numericalBinary(dataset, features):
    dataset[features] = np.where(dataset[features] >= dataset[features].mean(), 1, 0)

In [8]:
numericalBinary(dfTrain, ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week'])
numericalBinary(dfTest, ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week'])

In [9]:
dfTrain.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0    1       0              1             0             0               0   
1    0       1              0             0             0               0   
2    1       1              0             0             0               0   
3    0       1              1             0             0               0   
4    0       1              1             0             0               0   

  income  workclass_Federal-gov  workclass_Local-gov  workclass_Private  ...  \
0  <=50K                      0                    0                  0  ...   
1  <=50K                      0                    0                  1  ...   
2  <=50K                      0                    0                  1  ...   
3  <=50K                      0                    0                  1  ...   
4  <=50K                      0                    0                  1  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                        0                           0   
1                        0                           0   
2                        0                           0   
3                        0                           0   
4                        0                           0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                        0                     0                      0   
1                        0                     0                      0   
2                        0                     0                      0   
3                        0                     0                      0   
4                        0                     0                      0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                        0                               0   
1                        0                               0   
2                        0                               0   
3                        0                               0   
4                        0                               0   

   native-country_United-States  native-country_Vietnam  \
0                             1                       0   
1                             1                       0   
2                             1                       0   
3                             0                       0   
4                             1                       0   

   native-country_Yugoslavia  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  

[5 rows x 105 columns]

# Encoding the dependent variable

In [10]:
from sklearn.preprocessing import LabelEncoder

def encode_income(dataset):
    le = LabelEncoder()
    dataset['income'] = le.fit_transform(dataset['income'])
    return dataset

encode_income(dfTrain)
encode_income(dfTest)

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0        0       0              0             0             0               1   
1        0       1              1             0             0               0   
2        1       0              0             1             0               0   
4        0       1              0             0             0               0   
6        1       0              1             1             0               0   
...    ...     ...            ...           ...           ...             ...   
16274    0       1              1             0             0               0   
16275    1       1              1             0             0               0   
16277    0       1              1             0             0               1   
16278    1       0              1             1             0               0   
16279    0       0              1             0             0               1   

       income  workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0           0                      0                    0                  1   
1           1                      0                    1                  0   
2           1                      0                    0                  1   
4           0                      0                    0                  1   
6           1                      0                    0                  0   
...       ...                    ...                  ...                ...   
16274       0                      0                    0                  1   
16275       0                      0                    0                  1   
16277       0                      0                    0                  1   
16278       0                      0                    0                  1   
16279       1                      0                    0                  0   

       ...  native-country_Portugal  native-country_Puerto-Rico  \
0      ...                        0                           0   
1      ...                        0                           0   
2      ...                        0                           0   
4      ...                        0                           0   
6      ...                        0                           0   
...    ...                      ...                         ...   
16274  ...                        0                           0   
16275  ...                        0                           0   
16277  ...                        0                           0   
16278  ...                        0                           0   
16279  ...                        0                           0   

       native-country_Scotland  native-country_South  native-country_Taiwan  \
0                            0                     0                      0   
1                            0                     0                      0   
2                            0                     0                      0   
4                            0                     0                      0   
6                            0                     0                      0   
...                        ...                   ...                    ...   
16274                        0                     0                      0   
16275                        0                     0                      0   
16277                        0                     0                      0   
16278                        0                     0                      0   
16279                        0                     0                      0   

       native-country_Thailand  native-country_Trinadad&Tobago  \
0                            0                               0   
1                            0                               0   
2                            0                               0   
4                            0                         

In [17]:
X_train = dfTrain.loc[:, dfTrain.columns != 'income'].values
y_train = dfTrain['income'].values
X_test = dfTest.loc[:, dfTest.columns != 'income'].values
y_test = dfTest['income'].values

In [12]:
X_train

array([[1, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 0]], dtype=int64)

In [13]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
X_test

In [18]:
y_test

array([0, 1, 1, ..., 0, 0, 1])

# Building k-means clustering algorithm over the training set

## k value = 3

In [21]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(X_train)

KMeans(n_clusters=3)

In [22]:
from sklearn import metrics
score = metrics.accuracy_score(y_train, kmeans.predict(X_train))
print('Accuracy: {0:f}'.format(score))

Accuracy: 0.425185


In [23]:
kmeans.cluster_centers_

array([[ 2.79013292e-01,  4.78527607e-01,  2.74156442e-01,
         5.36809816e-02,  3.46370143e-02,  2.85020450e-01,
         2.70961145e-02,  4.93353783e-02,  7.88471370e-01,
         2.41564417e-02,  7.33640082e-02,  3.70654397e-02,
         5.11247444e-04,  3.47648262e-02,  4.89519427e-02,
         2.03220859e-02,  5.36809816e-03,  1.16308793e-02,
         1.63599182e-02,  1.82770961e-02,  3.11860941e-02,
         3.46370143e-02,  1.52862986e-01,  6.90184049e-03,
         3.39851738e-01,  3.64263804e-02,  2.30061350e-03,
         1.21421268e-02,  2.28016360e-01,  2.15362986e-01,
        -6.39679282e-18,  4.98466258e-03,  2.31339468e-02,
         6.91845603e-01,  4.66513292e-02,  1.80214724e-02,
         7.70705521e-02,  7.66871166e-04,  1.69350716e-01,
         8.85736196e-02,  4.69069530e-02,  9.61145194e-02,
         7.01687117e-02,  1.21037832e-01,  8.94683027e-04,
         1.00843558e-01,  2.50511247e-02,  1.08256646e-01,
         2.85020450e-02,  6.64621677e-02, -6.49480469e-1

## k value = 5

In [24]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(X_train)

KMeans(n_clusters=5)

In [25]:
score = metrics.accuracy_score(y_train, kmeans.predict(X_train))
print('Accuracy: {0:f}'.format(score))

Accuracy: 0.135274


In [26]:
kmeans.cluster_centers_

array([[ 6.50521921e-01,  4.13778706e-01,  1.00000000e+00,
         1.70981211e-01,  8.76826722e-02,  5.15240084e-01,
         4.36325678e-02,  8.58037578e-02,  6.13152401e-01,
         8.26722338e-02,  1.12317328e-01,  6.22129436e-02,
         2.08768267e-04,  1.35308431e-16,  5.13478149e-16,
        -7.80625564e-17, -2.94902991e-17,  1.73472348e-18,
        -6.24500451e-17,  1.33573708e-16,  7.70354906e-02,
         1.21503132e-01,  4.96868476e-01,  5.13569937e-02,
        -2.22044605e-15,  1.77035491e-01,  1.73472348e-17,
         7.62004175e-02, -2.44249065e-15,  1.06471816e-02,
         6.26304802e-04,  9.82672234e-01,  1.46137787e-03,
        -7.77156117e-16,  2.29645094e-03,  2.29645094e-03,
         4.59290188e-02,  2.08768267e-04,  8.26722338e-02,
         2.71189979e-01,  2.25469729e-02,  1.04384134e-02,
         1.79540710e-02,  1.58663883e-02,  2.08768267e-04,
         3.20459290e-01,  2.52609603e-02,  1.32776618e-01,
         3.77870564e-02,  1.67014614e-02,  9.76617954e-0

## k value = 10

In [27]:
kmeans = KMeans(n_clusters=10)
kmeans.fit(X_train)

KMeans(n_clusters=10)

In [28]:
score = metrics.accuracy_score(y_train, kmeans.predict(X_train))
print('Accuracy: {0:f}'.format(score))

Accuracy: 0.105932


In [29]:
kmeans.cluster_centers_

array([[ 6.43787575e-01,  4.28857715e-01,  1.54809619e-01, ...,
         9.26352705e-01,  5.01002004e-04, -1.19262239e-18],
       [ 5.92362507e-01,  4.30111456e-01, -2.49800181e-15, ...,
         9.03526402e-01,  1.64443632e-03,  5.48145441e-04],
       [ 9.04411765e-02,  5.05882353e-01,  2.57352941e-02, ...,
         8.92647059e-01,  3.92156863e-03,  4.90196078e-04],
       ...,
       [ 3.05651672e-01,  4.71164937e-01,  9.99423299e-01, ...,
         9.18108420e-01,  2.88350634e-03, -7.58941521e-19],
       [ 3.56671740e-01,  4.21106038e-01,  9.96955860e-01, ...,
         9.24403856e-01,  1.52207002e-03, -1.08420217e-18],
       [ 5.15316542e-01,  3.94145677e-01,  3.92784207e-01, ...,
         8.78829135e-01,  2.72294078e-03,  6.80735194e-04]])

# Applying the kNN algorithm on the last 10 records from the test set

In [45]:
dfTest = dfTest[-10:]
dfTest

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
16269    1       1              0             0             0               0   
16270    1       0              0             0             0               1   
16271    0       1              0             0             0               0   
16272    0       1              0             0             0               0   
16273    1       1              1             0             0               0   
16274    0       1              1             0             0               0   
16275    1       1              1             0             0               0   
16277    0       1              1             0             0               1   
16278    1       0              1             1             0               0   
16279    0       0              1             0             0               1   

       income  workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
16269       0                      0                    0                  1   
16270       0                      0                    0                  1   
16271       0                      0                    0                  1   
16272       0                      0                    0                  1   
16273       0                      0                    1                  0   
16274       0                      0                    0                  1   
16275       0                      0                    0                  1   
16277       0                      0                    0                  1   
16278       0                      0                    0                  1   
16279       1                      0                    0                  0   

       ...  native-country_Portugal  native-country_Puerto-Rico  \
16269  ...                        0                           0   
16270  ...                        0                           0   
16271  ...                        0                           0   
16272  ...                        0                           0   
16273  ...                        0                           0   
16274  ...                        0                           0   
16275  ...                        0                           0   
16277  ...                        0                           0   
16278  ...                        0                           0   
16279  ...                        0                           0   

       native-country_Scotland  native-country_South  native-country_Taiwan  \
16269                        0                     0                      0   
16270                        0                     0                      0   
16271                        0                     0                      0   
16272                        0                     0                      0   
16273                        0                     0                      0   
16274                        0                     0                      0   
16275                        0                     0                      0   
16277                        0                     0                      0   
16278                        0                     0                      0   
16279                        0                     0                      0   

       native-country_Thailand  native-country_Trinadad&Tobago  \
16269                        0                               0   
16270                        0                               0   
16271                        0                               0   
16272                        0                               0   
16273                        0                               0   
16274                        0                               0   
16275                        0                               0   
16277                        0                               0   
16278                        0  

In [46]:
for attributes in dfTrain.keys():
    if attributes not in dfTest.keys():
        print('Adding missing feature {}'.format(attributes))
        dfTest[attributes] = 0
        
dfTest = dfTest[dfTrain.keys()]

In [47]:
X_test = dfTest.loc[:, dfTest.columns != 'income'].values
y_test = dfTest['income'].values

In [48]:
X_test

array([[1, 1, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], dtype=int64)

In [49]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

## k value = 3

In [54]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

In [56]:
print('Accuracy: ' + str(accuracy_score(y_test, predictions)))
print(classification_report(y_test, predictions))

Accuracy: 0.8
              precision    recall  f1-score   support

           0       1.00      0.78      0.88         9
           1       0.33      1.00      0.50         1

    accuracy                           0.80        10
   macro avg       0.67      0.89      0.69        10
weighted avg       0.93      0.80      0.84        10



## k value = 5

In [57]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

In [58]:
print('Accuracy: ' + str(accuracy_score(y_test, predictions)))
print(classification_report(y_test, predictions))

Accuracy: 0.9
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.50      1.00      0.67         1

    accuracy                           0.90        10
   macro avg       0.75      0.94      0.80        10
weighted avg       0.95      0.90      0.91        10



## k value = 10

In [59]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

In [60]:
print('Accuracy: ' + str(accuracy_score(y_test, predictions)))
print(classification_report(y_test, predictions))

Accuracy: 0.9
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.50      1.00      0.67         1

    accuracy                           0.90        10
   macro avg       0.75      0.94      0.80        10
weighted avg       0.95      0.90      0.91        10

